### ISSUE TITLE
Can I emulate PMm with HCE?

### ISSUE THREAD

**Issue by wlt233** [OLIET2357/GeneralFelicaSimulator#1]

**Comment by wlt233** [comment]
in Sony's document it says Android only provide HCE Api for setting system code and NFCID2, but i wonder is there another way to change emulated PMm, thanks

**Comment by OLIET2357** [comment]
I think you can't.
Because PMm seems to be determined by the system, not the framework.
https://cs.android.com/android/platform/superproject/+/master:system/nfc/src/nfa/ce/nfa_ce_act.cc;l=331?q=t3tpmm&ss=android%2Fplatform%2Fsuperproject

**Comment by OLIET2357** [comment]
Besides, I have yet to see a reader confirming PMm.

**Comment by OLIET2357** [comment]
> I think you can't. Because PMm seems to be determined by the system, not the framework. https://cs.android.com/android/platform/superproject/+/master:system/nfc/src/nfa/ce/nfa_ce_act.cc;l=331?q=t3tpmm&ss=android%2Fplatform%2Fsuperproject

So technically it is possible, but you may need to burn a custom ROM instead of just rooting.

**Comment by wlt233** [comment]
thanks for reply! I'm just checking the source code of my rom and libnfc-nci.so from the phone, but it's hard to determine which part actually controls this t3tpmm.. I may keep trying

**Comment by OLIET2357** [comment]
I believe you can

**Comment by wlt233** [comment]
Maybe just add `<t3tPmm-filter android:name="[pmm]"/>` in host_nfcf_service.xml...

**Comment by OLIET2357** [comment]
The option doesn't work on Nexus 5X but DOES on Pixel 6a!
Maybe the old ones don't support it?
I made you work...

**Comment by wlt233** [comment]
The option was added by this commit in 2017: https://github.com/aosp-mirror/platform_frameworks_base/commit/ca26b128eaa54c0ecc103b34474ed42ec5f62516
So device after 2016 (which support HCE) and before 2017 may not support this option.

Don't mind, my Samsung S8 does not support it too. So I still need to modify my system as you pointed out ヾ(•ω•`)o

**Comment by OLIET2357** [comment]
I'm glad to hear that!
I'm going to add the PMm feature (^^)
