### ISSUE TITLE
system code problem

### ISSUE THREAD

**Issue by wlt233** [OLIET2357/GeneralFelicaSimulator#2]
If idm starts with  01 as first byte, syscode may not set properly that polling response only has idm and pmm (even polling command is 06 00 ff ff  01 00, 01 for request syscode). Maybe it is another restriction in rom.

**Comment by wlt233** [comment]
image here
![polling](https://i.ibb.co/PwLT4Xf/2023-04-08-000357.jpg)

**Comment by OLIET2357** [comment]
Unfortunately, I could not reproduce that behavior on Pixel 6a (see image).

![image](https://user-images.githubusercontent.com/50865315/230708441-ff42e773-e146-46de-a513-04c423442922.png)

HCE-F is unstable and often behaves differently from the document, and the behavior differs for each device.

And note that,
> There are cases where no Request Data is added even when specifying a Request Code.

rf. FeliCa Card User's Manual Excerpted Edition - 4.4.2 Polling

Therefore, this can be normal behavior as per FeliCa Standard.

**Comment by wlt233** [comment]
Thanks for your patience.

So could I confirm that polling is handle by lower NFC Controller (maybe under NCI (libnfc-nci.so)?), thus it's diffcult to control this response. Do you know where actually control this?

**Comment by OLIET2357** [comment]
Sorry, I don't know that.

I think it's a hint that the response is different for each model.

**Comment by wlt233** [comment]
I have just solved my problem using a workaround method. It turns out that when target card reader reads the card, it additively reads the ID block and use this result as card IDm instead using the IDm in polling response. So I just use 02fexxxx as IDm, so that the polling response sends syscode 88b4 which target card reader needs. Then I implement reading block in processNfcFPacket and send the real card data. Surprisingly it works. Anyway, thank you very much for your help!

**Comment by OLIET2357** [comment]
That's very good!
